export const supportedInputTypes = [
  'email', 'password', 'text',
  'color', 'date', 'datetime-local', 'month', 'number', 'range', 'hidden', 'search', 'tel', 'url', 'week',
];

export const errorMessages = {
  isAlpha: 'Please enter only letters',
  isAlphanumeric: 'Please enter only letters and numbers',
  isAscii: 'Please enter ASCII characters only',
  isBase64: 'Please enter a string that is base64 encoded',
  isBoolean: 'Please enter a boolean value',
  isCreditCard: 'Please enter a valid credit card number',
  isCurrency: 'Please enter a valid currency amount',
  isDataURI: 'Please enter a valid data uri format',
  isDecimal: 'Please enter a valid decimal number',
  isEmail: 'Please enter a valid email address',
  isEmpty: "You can't leave this blank",
  isFQDN: 'Please enter a valid fully qualified domain name',
  isFloat: 'Please enter a valid float value',
  isFullWidth: 'Please enter atleast one full-width character',
  isHalfWidth: 'Please enter atleast one half-width character',
  isHexColor: 'Please enter a valid hexadecimal color',
  isHexadecimal: 'Please enter a valid hexadecimal number',
  isISSN: 'Please enter a valid ISSN',
  isISIN: 'Please enter a valid ISIN',
  isISO8601: 'Please enter a valid ISO 8601 date',
  isISO31661Alpha2: 'Please enter a valid ISO 3166-1 alpha-2 officially assigned country code',
  isISRC: 'Please enter a valid ISRC',
  isInt: 'Please enter only an integer',
  isJSON: 'Please enter a valid JSON',
  isLatLong: 'Please enter a valid latitude-longitude coordinate',
  isLowercase: 'Please enter lowercase characters only',
  isMACAddress: 'Please enter a valid MAC address',
  isMD5: 'Please enter a valid MD5 hash',
  isMimeType: 'Please enter a valid MIME type format',
  isMongoId: 'Please enter a valid hex-encoded representation of a MongoDB ObjectId',
  isMultibyte: 'Please enter atleast one multibyte character',
  isNumeric: 'Please enter only numbers',
  isPort: 'Please enter a valid port number',
  isSurrogatePair: 'Please enter atlease one surrogate pair characters',
  isURL: 'Please enter a valid URL',
  isUUID: 'Please enter a valid UUID',
  isUppercase: 'Please enter only UPPERCASE characters',
  isVariableWidth: 'Please enter a mixture of full and half-width characters',
};

export const validatorDefinition = {
  contains: { mandatoryParams: ['str', 'seed'], optionalParams: [] },
  equals: { mandatoryParams: ['str', 'comparison'], optionalParams: [] },
  isAfter: { mandatoryParams: ['str'], optionalParams: ['date'] },
  isAlpha: { mandatoryParams: ['str'], optionalParams: ['locale'] },
  isAlphanumeric: { mandatoryParams: ['str'], optionalParams: ['locale'] },
  isAscii: { mandatoryParams: ['str'], optionalParams: [] },
  isBase64: { mandatoryParams: ['str'], optionalParams: [] },
  isBefore: { mandatoryParams: ['str'], optionalParams: ['date'] },
  isBoolean: { mandatoryParams: ['str'], optionalParams: [] },
  isByteLength: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isCreditCard: { mandatoryParams: ['str'], optionalParams: [] },
  isCurrency: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isDataURI: { mandatoryParams: ['str'], optionalParams: [] },
  isDecimal: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isDivisibleBy: { mandatoryParams: ['str', 'number'], optionalParams: [] },
  isEmail: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isEmpty: { mandatoryParams: ['str'], optionalParams: [] },
  isFQDN: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isFloat: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isFullWidth: { mandatoryParams: ['str'], optionalParams: [] },
  isHalfWidth: { mandatoryParams: ['str'], optionalParams: [] },
  isHash: { mandatoryParams: ['str', 'algorithm'], optionalParams: [] },
  isHexColor: { mandatoryParams: ['str'], optionalParams: [] },
  isHexadecimal: { mandatoryParams: ['str'], optionalParams: [] },
  isIP: { mandatoryParams: ['str'], optionalParams: ['version'] },
  isISBN: { mandatoryParams: ['str'], optionalParams: ['version'] },
  isISIN: { mandatoryParams: ['str'], optionalParams: [] },
  isISO31661Alpha2: { mandatoryParams: ['str'], optionalParams: [] },
  isISO8601: { mandatoryParams: ['str'], optionalParams: [] },
  isISRC: { mandatoryParams: ['str'], optionalParams: [] },
  isISSN: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isIn: { mandatoryParams: ['str', 'values'], optionalParams: [] },
  isInt: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isJSON: { mandatoryParams: ['str'], optionalParams: [] },
  isLatLong: { mandatoryParams: ['str'], optionalParams: [] },
  isLength: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isLowercase: { mandatoryParams: ['str'], optionalParams: [] },
  isMACAddress: { mandatoryParams: ['str'], optionalParams: [] },
  isMD5: { mandatoryParams: ['str'], optionalParams: [] },
  isMimeType: { mandatoryParams: ['str'], optionalParams: [] },
  isMobilePhone: { mandatoryParams: ['str', 'locale'], optionalParams: ['options'] },
  isMongoId: { mandatoryParams: ['str'], optionalParams: [] },
  isMultibyte: { mandatoryParams: ['str'], optionalParams: [] },
  isNumeric: { mandatoryParams: ['str'], optionalParams: [] },
  isPort: { mandatoryParams: ['str'], optionalParams: [] },
  isPostalCode: { mandatoryParams: ['str', 'locale'], optionalParams: [] },
  isSurrogatePair: { mandatoryParams: ['str'], optionalParams: [] },
  isURL: { mandatoryParams: ['str'], optionalParams: ['options'] },
  isUUID: { mandatoryParams: ['str'], optionalParams: ['version'] },
  isUppercase: { mandatoryParams: ['str'], optionalParams: [] },
  isVariableWidth: { mandatoryParams: ['str'], optionalParams: [] },
  isWhitelisted: { mandatoryParams: ['str', 'chars'], optionalParams: [] },
  matches: { mandatoryParams: ['str', 'pattern'], optionalParams: ['modifiers'] },
};
